export function getLocale(): 'zh' | 'en' {
  // Always default to zh for SSR/static build
  return 'zh';
}

export function t(key: string, locale: 'zh' | 'en' = 'zh'): string {
  const translations: Record<string, Record<string, string>> = {
    zh: {
      'nav.home': '首页',
      'nav.services': '服务',
      'nav.blog': '博客',
      'nav.about': '关于',
      'nav.contact': '联系',
      'hero.tagline': '专注硅碳负极 · 赋能电池创新',
      'hero.title': '锂离子电池硅碳负极材料\n专业技术解决方案',
      'hero.subtitle': '为初创电池企业提供从材料配方到产业化工艺的全流程技术支持',
      'hero.cta': '了解服务',
      'hero.ctaSecondary': '浏览博客',
      'stats.experience': '3年+ 研发团队管理经验',
      'stats.focus': '专注硅碳负极材料',
      'stats.clients': '服务初创电池企业',
      'services.title': '技术服务领域',
      'services.subtitle': '从材料设计到产业化，覆盖硅碳负极研发全流程',
      'blog.title': '技术博客',
      'blog.subtitle': '硅碳负极研发笔记、行业洞察与技术分析',
      'about.title': '关于锂硅新能',
      'about.mission': '让每一家初创电池企业都能获得专业的负极材料技术支持',
      'contact.title': '联系我们',
      'contact.subtitle': '欢迎联系，探讨技术合作',
      'contact.wechat': '微信扫码添加',
      'footer.copyright': '© 2026 杭州锂硅新能源有限公司',
      'common.lang': 'EN',
      'common.search': '搜索',
      'common.searchPlaceholder': '搜索文章...',
      'common.categories': '分类',
      'common.all': '全部',
      'common.share': '分享',
      'common.copy': '复制',
      'common.copied': '已复制',
      'common.backToTop': '返回顶部',
      'blog.backToBlog': '返回博客',
      'blog.viewAll': '查看全部文章',
      'services.viewAll': '查看全部服务',
      'blogList.title': '技术博客',
      'blogList.subtitle': '硅碳负极研发笔记、行业洞察与技术分析',
      'service.title': '技术服务',
      'service.subtitle': '从材料设计到产业化，覆盖硅碳负极研发全流程',
      'notFound.title': '页面未找到',
      'notFound.subtitle': '抱歉，您访问的页面不存在',
      'notFound.back': '返回首页',
    },
    en: {
      'nav.home': 'Home',
      'nav.services': 'Services',
      'nav.blog': 'Blog',
      'nav.about': 'About',
      'nav.contact': 'Contact',
      'hero.tagline': 'Silicon-Carbon Anode · Empowering Battery Innovation',
      'hero.title': 'Professional Technical Solutions\nfor Silicon-Carbon Anode Materials',
      'hero.subtitle': 'Providing full-process technical support from material formulation to industrialization for startup battery companies',
      'hero.cta': 'Our Services',
      'hero.ctaSecondary': 'Read Blog',
      'stats.experience': '3+ Years R&D Management',
      'stats.focus': 'Silicon-Carbon Anode Specialist',
      'stats.clients': 'Serving Startup Battery Companies',
      'services.title': 'Technical Services',
      'services.subtitle': 'From material design to industrialization, covering the full silicon-carbon anode R&D process',
      'blog.title': 'Technical Blog',
      'blog.subtitle': 'Silicon-carbon anode R&D notes, industry insights, and technical analysis',
      'about.title': 'About LiSi Energy',
      'about.mission': 'Enable every startup battery company to access professional anode material technical support',
      'contact.title': 'Contact Us',
      'contact.subtitle': 'Welcome to reach out for technical collaboration',
      'contact.wechat': 'Scan QR Code to Add WeChat',
      'footer.copyright': '© 2026 Hangzhou LiSi Energy Co., Ltd.',
      'common.lang': '中文',
      'common.search': 'Search',
      'common.searchPlaceholder': 'Search articles...',
      'common.categories': 'Categories',
      'common.all': 'All',
      'common.share': 'Share',
      'common.copy': 'Copy',
      'common.copied': 'Copied',
      'common.backToTop': 'Back to Top',
      'blog.backToBlog': 'Back to Blog',
      'blog.viewAll': 'View All Articles',
      'services.viewAll': 'View All Services',
      'blogList.title': 'Technical Blog',
      'blogList.subtitle': 'Silicon-carbon anode R&D notes, industry insights, and technical analysis',
      'service.title': 'Technical Services',
      'service.subtitle': 'From material design to industrialization, covering the full silicon-carbon anode R&D process',
      'notFound.title': 'Page Not Found',
      'notFound.subtitle': 'Sorry, the page you are looking for does not exist',
      'notFound.back': 'Back to Home',
    },
  };
  return translations[locale]?.[key] ?? key;
}

export const services = [
  {
    zh: { title: '硅碳负极材料配方优化', desc: '针对硅源、碳源、结构设计的配方优化，提升首效和循环稳定性' },
    en: { title: 'Silicon-Carbon Anode Formulation Optimization', desc: 'Formula optimization targeting silicon source, carbon source, and structural design to improve initial efficiency and cycle stability' },
  },
  {
    zh: { title: '电化学性能提升', desc: '解决容量衰减、极化增大、体积膨胀等核心难题' },
    en: { title: 'Electrochemical Performance Enhancement', desc: 'Solving core challenges: capacity decay, increased polarization, and volume expansion' },
  },
  {
    zh: { title: '产业化工艺指导', desc: '从实验室到中试的工艺放大，解决分散、涂布、辊压等生产难题' },
    en: { title: 'Industrial Process Guidance', desc: 'Process scale-up from lab to pilot production, solving dispersion, coating, and calendering challenges' },
  },
  {
    zh: { title: '材料表征与失效分析', desc: 'SEM/XRD/GC/TPD等表征分析，定位性能瓶颈，提供改进方向' },
    en: { title: 'Material Characterization & Failure Analysis', desc: 'SEM/XRD/GC/TPD and other characterization analysis to identify performance bottlenecks and improvement directions' },
  },
  {
    zh: { title: '技术路线评估', desc: '硅氧/硅碳/多孔硅等不同技术路线对比，帮助客户选择最优路径' },
    en: { title: 'Technology Route Assessment', desc: 'Comparison of silicon-oxide/silicon-carbon/porous silicon routes to help clients choose the optimal path' },
  },
  {
    zh: { title: '专利申请与知识产权保护', desc: '专利检索、布局规划、申请文件撰写，保护核心技术' },
    en: { title: 'Patent Application & IP Protection', desc: 'Patent search, layout planning, and application drafting to protect core technologies' },
  },
];
